-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.cupom DROP CONSTRAINT IF EXISTS "placaID_FK";

ALTER TABLE IF EXISTS public.tarifas DROP CONSTRAINT IF EXISTS "tipoVeiculoId_FK";

ALTER TABLE IF EXISTS public.placa DROP CONSTRAINT IF EXISTS "tipoVeiculo_FK";

ALTER TABLE IF EXISTS public.placa DROP CONSTRAINT IF EXISTS "modelo_FK";



DROP TABLE IF EXISTS public.cupom;

CREATE TABLE IF NOT EXISTS public.cupom
(
    id bigserial NOT NULL,
    "dataHoraEntrada" time without time zone NOT NULL,
    "dataHoraSaida" timestamp without time zone,
    descricao character varying(100),
    "valorTotal" numeric(10, 2),
    "placaID" bigserial,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.tarifas;

CREATE TABLE IF NOT EXISTS public.tarifas
(
    id bigserial NOT NULL,
    "horaCobrada" time without time zone NOT NULL,
    "tipoVeiculoId" bigserial NOT NULL,
    valor numeric(10, 2) NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."tipoVeiculo";

CREATE TABLE IF NOT EXISTS public."tipoVeiculo"
(
    id bigserial NOT NULL,
    veiculo character varying(10) NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.placa;

CREATE TABLE IF NOT EXISTS public.placa
(
    id bigserial NOT NULL,
    placa character varying(7) NOT NULL,
    "modeloId" bigserial NOT NULL,
    "tipoVeiculoId" bigserial NOT NULL,
    cor character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.modelo;

CREATE TABLE IF NOT EXISTS public.modelo
(
    id bigserial NOT NULL,
    "nomeModelo" character varying(50)[] NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.cupom
    ADD CONSTRAINT "placaID_FK" FOREIGN KEY ("placaID")
    REFERENCES public.placa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tarifas
    ADD CONSTRAINT "tipoVeiculoId_FK" FOREIGN KEY ("tipoVeiculoId")
    REFERENCES public."tipoVeiculo" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.placa
    ADD CONSTRAINT "tipoVeiculo_FK" FOREIGN KEY ("tipoVeiculoId")
    REFERENCES public."tipoVeiculo" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.placa
    ADD CONSTRAINT "modelo_FK" FOREIGN KEY ("modeloId")
    REFERENCES public.modelo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;