-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public."Cupom" DROP CONSTRAINT IF EXISTS "PlacaID_FK";

ALTER TABLE IF EXISTS public."Tarifas" DROP CONSTRAINT IF EXISTS "tipoVeiculo_FK";

ALTER TABLE IF EXISTS public."Placa" DROP CONSTRAINT IF EXISTS "tipoVeiculo_FK";

ALTER TABLE IF EXISTS public."Placa" DROP CONSTRAINT IF EXISTS "modeloId_FK";



DROP TABLE IF EXISTS public."Cupom";

CREATE TABLE IF NOT EXISTS public."Cupom"
(
    id bigint NOT NULL,
    "dataHoraEntrada" timestamp with time zone NOT NULL,
    "dataHoraSaida" timestamp with time zone,
    descricao character varying(100),
    "valorTotal" numeric(10, 2),
    "placaID" bigint,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."Tarifas";

CREATE TABLE IF NOT EXISTS public."Tarifas"
(
    id bigint NOT NULL,
    hora time with time zone NOT NULL,
    "tipoVeiculoId" bigint NOT NULL,
    valor numeric(10, 2),
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."tipoVeiculo";

CREATE TABLE IF NOT EXISTS public."tipoVeiculo"
(
    id bigint NOT NULL,
    veiculo character varying(10) NOT NULL,
    CONSTRAINT "TipoVeiculoId_UK" UNIQUE (id)
);

DROP TABLE IF EXISTS public."Placa";

CREATE TABLE IF NOT EXISTS public."Placa"
(
    id bigint NOT NULL,
    "modeloId" bigint,
    placa character varying(7) NOT NULL,
    "tipoVeiculoId" bigint,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."Modelo";

CREATE TABLE IF NOT EXISTS public."Modelo"
(
    id bigint NOT NULL,
    "nomeModelo" character varying(50),
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Cupom"
    ADD CONSTRAINT "PlacaID_FK" FOREIGN KEY ("placaID")
    REFERENCES public."Placa" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Tarifas"
    ADD CONSTRAINT "tipoVeiculo_FK" FOREIGN KEY ("tipoVeiculoId")
    REFERENCES public."tipoVeiculo" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Placa"
    ADD CONSTRAINT "tipoVeiculo_FK" FOREIGN KEY ("tipoVeiculoId")
    REFERENCES public."tipoVeiculo" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Placa"
    ADD CONSTRAINT "modeloId_FK" FOREIGN KEY ("modeloId")
    REFERENCES public."Modelo" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;