name: Run Cypress Tests

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  
  cypress:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: verceldb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Check out the code
      - name: Check out the repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      # Instalar dependências
      - name: Install dependencies
        run: |
          npm install

      # Instalar o ngrok para expor o servidor
      - name: Install ngrok
        run: |
          npm install -g ngrok

      # Iniciar o servidor Next.js em segundo plano
      - name: Start Next.js server
        run: |
          npm run dev &
          echo $! > .next.pid  # Salva o PID do processo para matá-lo depois
        env:
          NEXT_PUBLIC_API_URL: 'http://localhost:3000'

      # Espera o servidor Next.js iniciar
      - name: Wait for Next.js server
        run: npx wait-on http://localhost:3000

      # Expor o servidor Next.js usando ngrok
      - name: Expose server with ngrok
        run: |
          ngrok http 3000 --log=stdout > ngrok.log &
          sleep 5  # Aguarda ngrok gerar a URL pública
          export PUBLIC_URL=$(tail -n 1 ngrok.log | grep -o 'https://[0-9a-z]*\.ngrok.io')  # Extrai a URL pública
          echo "Next.js is available at: $PUBLIC_URL"
          echo "PUBLIC_URL=$PUBLIC_URL" >> $GITHUB_ENV  # Define a URL como variável de ambiente

      # Instalar dependências do Cypress
      - name: Install Cypress dependencies
        run: npm install cypress

      # Executar os testes do Cypress
      - name: Run Cypress tests
        run: npx cypress run --config baseUrl=$PUBLIC_URL

      